robx/pzprjs

src/variety/curvedata.js

Fixes #66.
Instead of only using the four immediate neighbours of a node, the connections array now contains all positions along a certain axis. [This puzzle](https://puzz.link/p?curvedata/20/20/0zzzzzzzzzzzzzzzzzzzy/20/20/fffffffffbfffffffffbfffffffffbfffffffffbfffffffffbfffffffffbfffffffffbfffffffffbfffffffffbfffffffffbfffffffffbfffffffffbfffffffffbfffffffffbfffffffffbff7ffffffbfffffffffbfffffffffbfffffffffb5555555551) can now entirely avoid iterating through the different combinations.

Use more distinct keys in Curve Data checker

---

src/puzzle/Piece.js
src/variety-common/MouseInput.js
src/variety/bonsan.js
src/variety/herugolf.js
src/variety/yosenabe.js

https://github.com/robx/pzprjs/issues/1#issuecomment-494007516
This patch also prevents objects that are being dragged from losing focus (by not changing `mouseCell` when line placement fails).

Prevent drawing curves in moving puzzles

---

src-ui/js/ui/Event.js
src-ui/p.html
src/puzzle/Config.js
src/puzzle/Graphic.js
src/puzzle/KeyInput.js
src/puzzle/MouseInput.js
src/puzzle/Operation.js
src/variety-common/Graphic.js
src/variety/easyasabc.js
src/variety/starbattle.js

Experimental feature to mark the beginning of a trial. Presently, when rejecting a trial it marks the position of the start of the trial. It would be nicer to instead draw the start of the trial differently right away and keep it visible.

Trialmarker

---

src/variety/kurotto.js

This is a minor annoyance, but it always bugged me that circles without an explicit numeric clue would never go grey while solving a Kurotto (to indicate that they have been satisfied, as it does with the numeric clues). This change should ensure that they are marked as grey at all times (because they can indeed never be unsatisfied).

Kurotto: Mark unspecified givens as satisfied

---

src/variety/juosan.js

I think vertical bars are easier to count, so I chose this as the default (but it is otherwise entirely arbitrary).

Juosan: Mark vertical bars in nonstrict majorities

---

src-ui/js/ui/ToolArea.js
src-ui/p.html
src/variety/country.js
src/variety/doppelblock.js
src/variety/renban.js

Thank you for answering my questions in #15 !
This time, I have translated into japanese for doppel-block, renban and maxi-loop in addition to some messages related to my questions.
About line 199 in  src-ui/js/ui/ToolArea.js, the new sentence I suggest may be too long. If there is a problem to display this word, I will re-translate it.

doppel-block, maxi-loop, curve-data, renban: translate some msgs

---

Changelog.md
docs/Config.md
docs/Puzzle.md
src-ui/js/ui/Event.js
src-ui/js/ui/MenuArea.js
src/puzzle/Graphic.js
src/variety-common/Graphic.js
src/variety/country.js
src/variety/fillmat.js
src/variety/hakoiri.js
src/variety/hanare.js
src/variety/hebi.js
src/variety/kaero.js
src/variety/kinkonkan.js
src/variety/nawabari.js
src/variety/nurikabe.js
src/variety/roma.js
src/variety/shikaku.js
src/variety/shimaguni.js
src/variety/tateyoko.js
src/variety/toichika.js
test/script/tateyoko.js

This has a couple of straightforward and a couple of rather experimental changes.
- reword a lot of error messages, to get rid of "plural" mostly
- fix the shakashaka triangle drawing to align short triangle edges with given shaded cells
- use `devicePixelRatio` when available to
1. draw grid lines with a width that's a multiple of actual pixel size
2. draw grid lines with width below 1 at low resolutions on high dpi displays
- change the dashing count to a minimum of 4 (from 3 before)
- draw the chassis (frame around the puzzle) towards the outside, instead of centered; this should mean that cells next to the edge of the grid are more square; e.g. noticably masyu clues will appear less close to the edge
This PR is live for testing at https://garp.vllmrt.net/scratch/various.
Todo:

Various changes, mostly graphical

---

src-ui/css/ui.css
src-ui/js/pzpr-ui.js
src-ui/js/ui/Boot.js
src-ui/js/ui/Listener.js
src-ui/js/ui/MenuArea.js
src-ui/js/ui/Network.js
src-ui/js/ui/PopupMenu.js
src-ui/js/ui/ToolArea.js
src-ui/js/ui/UI.js
src-ui/p.html
src/puzzle/Operation.js
src/variety/kouchoku.js

This adds cooperative network play, the server component handled by https://github.com/robx/puzzld.
Current state:
- network play can be activated through a popup (generating a shareable link) or by loading from such a shareable link
- during network play
- any piece changes (that didn't come from the server) are sent to the server
- any piece changes that come from the server are applied to the board
Current limitations:
- interaction with trial mode and history is unclear and probably broken
- ~~if you join late, you start with an empty board~~
- no support for non-piece operations
- the puzzle definition itself is not communicated
- pretty hacky, but in an isolated way
It's already pretty fun, so I'd like to merge this soon. I think it should be ok with the following changes:

Network play

---

src/puzzle/Operation.js
src/variety/tents.js

Partial #184
* All errors and info is cleared when rejecting a trial. This should happen for all puzzle types.
* When inside a trial mode, qinfo tents are always drawn with a trial color

Tents: Various trial fixes for qinfo

---

src-ui/p.html
src-ui/rules.html
src/pzpr/variety.js
src/variety-common/Answer.js
src/variety/aquarium.js
src/variety/balance.js
src/variety/cbblock.js
src/variety/country.js
src/variety/haisu.js
src/variety/kazunori.js
src/variety/kouchoku.js
src/variety/kurodoko.js
src/variety/nanro.js
src/variety/nurimaze.js
src/variety/paintarea.js
src/variety/snake.js
src/variety/tents.js
src/variety/yinyang.js

Compare #15. Some of these change existing Japanese translations; I can't judge whether those are actually improvements. I didn't understand the input mode part for Tents and Trees -- does this mean that I should just leave "Tents" and "Trees" input mode labels in English?
@domishana Do you have an opinion on the changes here?

Update Japanese translations based on twitter-shared document

---

src/variety/box.js

Previously, the row and column checks were swapped -- for example, when
editing a puzzle with 10 columns and 3 rows, it would allow entering
numbers from 0-55 along the top and 0-6 along the left.

box: fix editor validity check

---

src-ui/js/ui/Boot.js
src-ui/p.html
src-ui/sw.js

This adds a service worker that caches `https://puzz.link/p` regardless of query parameters. It's live currently.
The intended effect is that once loaded, the HTML for any player links will be loaded from the service worker. Particularly, this *should* speed up load times significantly from across the globe.
Main potential downside that I see right now is this adds complexity, and might make p.html be cached in a more sticky way, causing trouble when p.html needs changes.

Service worker

---

src/variety/hitori.js

Currently, Hitori clues 16 through 35 are incorrectly encoded as `-g` through `-z` instead of `g` through `z`
e.g. try exporting this to URL:
https://puzz.link/p?type=editor&pzprv3/hitori/7/7/1%2014%201%2015%201%2016%201%20/17%201%2018%201%2019%201%2020%20/1%2021%201%2022%201%2023%201%20/24%201%2025%201%2026%201%2027%20/1%2028%201%2029%201%2030%201%20/31%201%2032%201%2033%201%2034%20/1%2035%201%2036%201%2037%201%20/.%20.%20.%20.%20.%20.%20.%20/.%20.%20.%20.%20.%20.%20.%20/.%20.%20.%20.%20.%20.%20.%20/.%20.%20.%20.%20.%20.%20.%20/.%20.%20.%20.%20.%20.%20.%20/.%20.%20.%20.%20.%20.%20.%20/.%20.%20.%20.%20.%20.%20.%20//

hitori: fix encoding of numbers >=16

---

src/.eslintrc.json

It's noisy in PR diffs, and we can't really easily fix it right now because as I understand it, the correct fix would be to use `let` but we're still writing ES5 for the moment.

eslint: turn off no-redeclare

---

Makefile
src/variety/country.js

simpleloop, doubleback, rassi: "empty" cell drawing tweaks
- move the grid drawing earlier, so that the empty cell shading
covers the grid lines (so we don't see the dashed lines when
we don't draw borders)
- for simpleloop, avoid drawing thick borders around empty cells,
to fix ugliness when two empty cells touch diagonally
- for doubleback and rassi, that fix doesn't work due to room
borders, so instead shade empty cells dark gray (and don't draw
borders between empty cells)

simpleloop, doubleback, rassi: "empty" cell drawing tweaks

---

src/variety/tawa.js

This new color makes it easier to distinguish adjacent cells, which is an issue that has been reported by some users on Discord.

tawa: Change shade color

---

src-ui/p.html

This was hidden away in the menus, where nobody thinks to look for a genre-specific setting. The panel currently hosts display options for Yajilin, International Borders, Hebi-Ichigo, Context and Koburin.

yinyang: Move display setting to Panel

---

src/variety-common/Encode.js
test/variety/shwolf_test.js

The encoding of the dots (encodeCrossMarks) was emitting an empty string, while the decoding was consuming one character.
The change encodes the crosses of such a grid as "0", which is consistent in that absence of crosses is generally encoded as the number of potential crosses, i.e., all crosses are skipped.
The only other puzzle type that uses encodeCrossMarks is bdblock,
which uses it with `cross: 2` hence is not affected.

shwolf: fix encoding of 1xn and nx1 grids (fixes #262)

---

src/variety/lapaz.js

Originally I just wanted to do something about the dark green borders (they're barely distinguishable from black and look a bit "dirty" to me).
As a side effect that I don't understand at all, left clicking a shaded cell now turns it explicitly unshaded. I'm not sure why this previously turned back to entirely unset -- was that deliberate or an accidental side-effect of the ghost border implementation?

lapaz: simplify graph handling, tweak style

---

src-ui/js/ui/MenuConfig.js
src/variety/chainedb.js
src/variety/dominion.js

There seems to be no real need for it for these puzzles -- you generally know they're done when you place the last black cell. (There might well be a couple more among the new puzzles that could have it removed.)
Also restores the default autocheck setting to guarded, which I missed in the merge.

remove autocheck guard for dominion and chained block

---

src-ui/js/ui/ToolArea.js
src-ui/p.html
src-ui/res/p.en.json
src/variety/slither.js
test/variety/slither_test.js
test/variety/slitherlink_test.js

I solve slitherlink puzzles via shading the cells, which has some advantages (easier to see connectivity, less inputs required overall).  However at the end of the puzzle this requires going back over in Line mode and outlining all the green cells in order for the answer checker to trigger.  I added a button to do this outlining automatically so that the experience of solving via shading is more user-friendly.
Here are before/after screenshots showing the new button's behavior.

Add "Outline shaded cells" button to slitherlink

---

src/puzzle/Operation.js

It seems that there exists an undo bug. This request is to fix the bug.
1. open the pencils page
2. change the mode to play mode
3. click the same edge twice
then, ctrl+z cannot delete the edge anymore.
previously, the `opemgr` removes the last element of the history object if the `lastope` is noop.
however, this element is an array of operations, and may have other operation than the `lastope`, so this action may lose some other operation from histories.

fix undo behavior

---

src/variety/bosnianroad.js
test/script/bosnianroad.js

While Auto mode worked correctly for this, using Shaded Cells or Unshaded Cells modes while solving would place or remove gray cells instead, allowing the player to erase the puzzle. Whoops.
More subtly, placing gray cells while editing would fail to erase underlying shaded/unshaded cells.
This PR fixes both bugs.

Fix Bosnian Road shading input

---

src/variety/tasquare.js

Adding "grey correct numbers" to Tasquare

---

src/variety/dominion.js

I have noticed that there is no check for if numbers are actually shaded. Given that it is impossible to shade them in normal play, is this fine?

Fix question marks for Dominion
