robx/pzprjs

- src/variety-common/Answer.js
- src/variety/kaero.js
- src/variety/tatamibari.js
These are probably better than the original, but suggestions welcome. Also please add suggestions for other failure message changes!
> reword some english language failure messages

- src/variety-common/Graphic.js
- test/puzzle/render_test.js
This seems to not necessarily be the right way to fix it, but it'll do for now.
> Fix render bug introduced by fillomino border drawing (fixes #17)

- src/variety/kurodoko.js
> Nurimisaki: Move shaded 2x2 rule to top

- src/variety-common/Graphic.js
- src/variety/pipelink.js
> Loopsp bleed

- Changelog.md
- src/variety/cbblock.js
- test/script/test_cbblock.js
- test/variety/cbblock_test.js
> Cbblock bug

- src-ui/p.html
I got annoyed that I can't click the text of the option, which a `<label for="..">` can solve.
This PR would fix it, but I have no idea if the translation stuff still works when I change a span into a label. Otherwise I'll make them all `<label><span>...</></>`.
Will make a proper PR once I know which one works.
> use <label> for option checkboxes

- src/variety/pencils.js
I have translated error messages for pencils into Japanese.
#15
> translate error messages for pencils into Japanese

- src/variety/cbblock.js
- src/variety/curvedata.js
- src/variety/heyawake.js
- src/variety/kurodoko.js
- src/variety/nawabari.js
- src/variety/yajilin.js
I have translated error messages for ∀人∃HEYA, yajirin, heteromino, nurimisaki, curve-data, double-choco into Japanese.
#15 
I send all changes in this PR this time:)
> translate error msgs for some puzzles into Japanese.

- src-ui/p.html
- src/variety/aquarium.js
- src/variety/castle.js
- src/variety/compass.js
- src/variety/country.js
I translate some messages into Japanese:)
- doubleback
- compass
- castle walls
- aquaplace
#15
> Translate for some messages into Japanese

- Changelog.md
- src-ui/css/sc8.css
- src-ui/js/ui/Listener.js
- src-ui/js/ui/MenuArea.js
- src-ui/js/ui/MenuConfig.js
- src-ui/js/ui/ToolArea.js
- src-ui/p.html
- src/puzzle/Config.js
- src/puzzle/FileData.js
- src/variety/country.js
- src/variety/numlin.js
> variant overhaul

- src/puzzle/Address.js
- src/puzzle/Board.js
- src/puzzle/BoardExec.js
- src/puzzle/KeyInput.js
- src/variety-common/Encode.js
- src/variety-common/FileData.js
- src/variety-common/Graphic.js
- src/variety/starbattle.js
- src/variety/tentaisho.js
This is a prerequisite for implementing [Mid-loop](https://www.nikoli.co.jp/en/puzzles/mid-loop.html) in a separate file, as opposed to a variant of a completely unrelated puzzle type.
> Refactor: Move Dot logic from starbattle/tentaisho to shared classes

- src/puzzle/Operation.js
- src/puzzle/Piece.js
- test/variety/herugolf_test.js
> Herugolf fix by disabling prehooks on undo/redo

- src/variety/shakashaka.js
Based on how it's implemented in Castle Wall and Wall Logic.
> Shakashaka: Autogrey satisfied givens

- src/variety/shakashaka.js
This implements the first option discussed in #142
> shakashaka: only autocmp when all cells are marked

- src-ui/p.html
- src/pzpr/variety.js
- src/variety/midloop.js
translate some messages for midloop and curvedata into japanese:)
and, fix some massages, for example, __About__.
> translate messages for midloop and curvedata into japanese

- src/variety/haisu.js
> haisu: Set maxnum based on room size

- src/variety/tawa.js
> Small typo fix in Tawa rules

- src/variety-common/FileData.js
- src/variety/haisu.js
- src/variety/icebarn.js
- src/variety/nagare.js
This moves the saving function of lines + directional marks from icebarn to a shared class.
> haisu: Fix saving of dir. aux. marks

- src/variety/box.js
- test/script/box.js
> box: fix editor validity check

- src/variety/nanro.js
Fix #246 
If a room contains numbers, treat all circles as the same number.
If a room contains only circles, treat the room as empty.
> nanro : fix invalid solutions with circles

- src/variety/tapa.js
- test/script/tapa.js
> tapa: Repair input modes

- src/variety/kurochute.js
> kurochute: Fix number completion overriding errors

- src/pzpr/event.js
> Unregister Service Worker in src-ui

- src/variety/kakuru.js
> numrope: Clear snum on number drag

- src-ui/js/list.js
- vercel.json
> Repair Vercel preview environments

- src/variety/aquarium.js
- test/script/aquarium.js
> aquarium: Add manual number qcmp

- src/puzzle/Config.js
- src/pzpr/env.js
> Improve touchevent detection for Android 13

- test/script/arukone.js
> arukone: Change example puzzle

- src-ui/css/ui.css
- src-ui/js/ui/Notify.js
- src-ui/js/ui/PopupMenu.js
> Fix dragging panel with touch events

- src/variety/castle.js
- test/script/castle.js
> castle editor: set colors with g/w/b

- src/variety-common/BoardExec.js
- src/variety/amibo.js
- src/variety/gokigen.js
- src/variety/juosan.js
- src/variety/kinkonkan.js
- src/variety/ladders.js
- src/variety/lollipops.js
- src/variety/nagare.js
- src/variety/pencils.js
- src/variety/pipelink.js
- src/variety/reflect.js
- src/variety/slalom.js
- src/variety/slashpack.js
- src/variety/tatamibari.js
- src/variety/tateyoko.js
- src/variety/walllogic.js
- test/puzzle/boardexec_test.js
> Avoid recording operations during board adjust

- src/variety-common/MouseInput.js
- test/script/oyakodori.js
> Don't erase moveline when erasing peke

- src-ui/js/ui/MenuConfig.js
- src-ui/js/ui/ToolArea.js
- src-ui/p.html
- src-ui/res/p.en.json
- src-ui/res/p.ja.json
- src/puzzle/Config.js
> Add option to hide timer

- src-ui/js/list.js
- src-ui/js/ui/MenuConfig.js
- src-ui/js/ui/Timer.js
- src/puzzle/Config.js
>  Use timer to save configuration 
